
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 16 20:33:50 UYT 2014
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int FUNCTION = 39;
  public static final int STRING_LITERAL = 3;
  public static final int GREATER_OR_EQUAL = 22;
  public static final int EQUALS = 9;
  public static final int CONTINUE = 37;
  public static final int LPAREN = 11;
  public static final int GREATER = 19;
  public static final int PTO_COMMA = 30;
  public static final int LESS = 20;
  public static final int FOR = 33;
  public static final int MINUS = 14;
  public static final int RPAREN = 12;
  public static final int NOT = 10;
  public static final int AND = 8;
  public static final int DOUBLE_MINUS = 16;
  public static final int OPEN_ARRAY = 26;
  public static final int LESS_OR_EQUAL = 21;
  public static final int OR = 7;
  public static final int COMMA = 28;
  public static final int OPEN_BLOCK = 31;
  public static final int PLUS = 13;
  public static final int IF = 34;
  public static final int EOF = 0;
  public static final int NaN = 25;
  public static final int BOOLEAN = 2;
  public static final int PTO = 29;
  public static final int RETURN = 38;
  public static final int NUMERIC_LITERAL = 4;
  public static final int EQUAL = 6;
  public static final int error = 1;
  public static final int DISTINCT = 23;
  public static final int NULL = 24;
  public static final int BREAK = 36;
  public static final int CLOSE_ARRAY = 27;
  public static final int OBELUS = 18;
  public static final int TIMES = 17;
  public static final int ELSE = 35;
  public static final int DOUBLE_PLUS = 15;
  public static final int CLOSE_BLOCK = 32;
  public static final int VAR = 5;
  public static final int IDENTIFIER = 40;
}

